FROM itdoginfo/openwrt-sdk-apk:25.12.3

ARG PODKOP_VERSION
ENV PODKOP_VERSION=${PODKOP_VERSION}
ENV PODKOP_PACKAGE_FORMAT=apk

COPY ./krot /builder/package/feeds/utilities/krot
COPY ./luci-app-krot /builder/package/feeds/luci/luci-app-krot

RUN make defconfig && \
    make package/krot/compile -j4 V=s && \
    make package/luci-app-krot/compile -j4 V=s && \
    mkdir -p /builder/output && \
    find /builder/bin -name '*.apk' -exec cp {} /builder/output/ \;
