#!/bin/sh
# openflux-run.sh <section> — runs one OpenFlux exit node under procd and keeps
# the kernel from RST-ing the tunnel connections in l3 mode.
#
# Upstream CLI (https://github.com/p1neappleXpress/OpenFlux):
#   openflux --role=exit --mode=l3|l4 --transport=yandex|vyandex|oneme|
#            cupsonline|mailru --url=... [--maxToken=...] [--maxUid=...]
#            [--codec=batched|legacy] [--local-ip=...]
#            [--encryption-key-file=...] [--debug]
#
# RST suppression (issue #44): in l3 the Linux kernel sees reply packets for
# connections it did not open and sends TCP RSTs that break the tunnel. The
# runner installs a scoped drop rule for RSTs generated by the kernel.
# Note: no `set -u` — OpenWrt /lib/functions.sh is not nounset-safe.

CONFIG_NAME="krot_openflux"
SECTION="${1:-}"
[ -n "$SECTION" ] || { echo "usage: $0 <section>" >&2; exit 1; }
[ -f "/etc/config/${CONFIG_NAME}" ] || exit 0

OF_DIR="/opt/openflux"
BIN="${OF_DIR}/openflux"
STATE_DIR="/etc/openflux"
NFT_TABLE="krot_openflux"
IPT_CHAIN="KROT_OPENFLUX"

export IPKG_INSTROOT="${IPKG_INSTROOT:-}"
. /lib/functions.sh
config_load "$CONFIG_NAME"

enabled="$(config_get_bool "$SECTION" "enabled" 1)"
[ "$enabled" = "0" ] && exit 0

config_get label "$SECTION" "label" "$SECTION"
config_get transport "$SECTION" "transport" "yandex"
config_get exit_mode "$SECTION" "exit_mode" "l3"
config_get url "$SECTION" "url" ""
config_get max_token "$SECTION" "max_token" ""
config_get max_uid "$SECTION" "max_uid" ""
config_get listen_port "$SECTION" "listen_port" "4545"
config_get codec "$SECTION" "codec" "batched"
config_get encryption_key "$SECTION" "encryption_key" ""
config_get local_ip "$SECTION" "local_ip" ""
config_get debug "$SECTION" "debug" "0"
config_get suppress_rst "settings" "suppress_rst" "1"
config_get use_iptables "settings" "use_iptables" "0"

# Performance tuning via UCI (optional, see README)
config_get batch_bytes "$SECTION" "batch_bytes" "65536"
config_get batch_count "$SECTION" "batch_count" "256"
config_get batch_linger_ms "$SECTION" "batch_linger_ms" "1"
config_get volga_workers "$SECTION" "volga_workers" "4000"
config_get volga_batch_size "$SECTION" "volga_batch_size" "50"
config_get volga_batch_timeout "$SECTION" "volga_batch_timeout" "1"
config_get volga_batch_bytes "$SECTION" "volga_batch_bytes" "8388608"

log() { logger -t "krot-openflux[$SECTION]" -- "$*"; echo "krot-openflux[$SECTION]: $*"; }

if [ ! -x "$BIN" ]; then
    log "binary $BIN is missing; set bin_base on http://<router-ip>/openflux/ and press Update, or copy the binary manually"
    exit 1
fi

case "$exit_mode" in
    l3|l4) ;;
    *) log "unknown exit_mode '$exit_mode', falling back to l4"; exit_mode="l4" ;;
esac

case "$codec" in
    batched|legacy) ;;
    *) log "unknown codec '$codec', falling back to batched"; codec="batched" ;;
esac

# Validate transport-specific inputs before touching the firewall.
case "$transport" in
    yandex|vyandex|mailru)
        [ -n "$url" ] || { log "transport '$transport' requires option url (doc URL)"; exit 1; }
        ;;
    oneme)
        [ -n "$max_token" ] && [ -n "$max_uid" ] || { log "transport 'oneme' requires max_token and max_uid"; exit 1; }
        ;;
    cupsonline)
        [ -n "$url" ] || { log "transport 'cupsonline' requires option url (base64 room list printed by the exit node)"; exit 1; }
        ;;
    *)
        log "unknown transport '$transport'"
        exit 1
        ;;
esac

mkdir -p "$STATE_DIR"

# ---------------------------------------------------------------------------
# Kernel RST suppression for l3 mode (scoped to the tunnel egress when
# --local-ip is set, host-wide otherwise). Idempotent.
# ---------------------------------------------------------------------------

rst_rule_present() {
    if command -v nft >/dev/null 2>&1 && [ "$use_iptables" != "1" ]; then
        # Table alone is not enough: the drop rule itself must be there.
        nft list chain ip "$NFT_TABLE" output 2>/dev/null | grep -q 'tcp flags.*drop'
    elif command -v iptables >/dev/null 2>&1; then
        iptables -t filter -nL "$IPT_CHAIN" 2>/dev/null | grep -q DROP
    else
        return 1
    fi
}

rst_rule_install() {
    if command -v nft >/dev/null 2>&1 && [ "$use_iptables" != "1" ]; then
        # Several instances share one table; a concurrent start may have
        # installed the rule already. Check before adding a duplicate.
        rst_rule_present && return 0
        nft add table ip "$NFT_TABLE" 2>/dev/null || true
        nft add chain ip "$NFT_TABLE" output '{ type filter hook output priority -1 ; }' 2>/dev/null || true
        # nft rejects `tcp flags & (tcp-rst) != 0` ("Could not parse TCP flag
        # expression"); use symbolic flag names. Pass the rule as ONE quoted
        # argument so it is parsed exactly as if typed on the command line.
        if [ -n "$local_ip" ]; then
            nft "add rule ip $NFT_TABLE output ip saddr $local_ip tcp flags & rst == rst counter drop" 2>/dev/null || true
        else
            nft "add rule ip $NFT_TABLE output tcp flags & rst == rst counter drop" 2>/dev/null || true
        fi
        if rst_rule_present; then
            log "kernel RST suppression active (nft: $NFT_TABLE)"
        else
            log "WARNING: failed to install the nft RST drop rule; l3 tunnels may be broken by kernel RSTs"
        fi
    elif command -v iptables >/dev/null 2>&1; then
        iptables -t filter -N "$IPT_CHAIN" 2>/dev/null || true
        iptables -t filter -F "$IPT_CHAIN" 2>/dev/null || true
        if [ -n "$local_ip" ]; then
            iptables -t filter -A "$IPT_CHAIN" -s "$local_ip" -p tcp --tcp-flags RST RST -j DROP 2>/dev/null || true
        else
            iptables -t filter -A "$IPT_CHAIN" -p tcp --tcp-flags RST RST -j DROP 2>/dev/null || true
        fi
        iptables -t filter -C OUTPUT -p tcp --tcp-flags RST RST -j "$IPT_CHAIN" 2>/dev/null || \
            iptables -t filter -I OUTPUT 1 -p tcp --tcp-flags RST RST -j "$IPT_CHAIN" 2>/dev/null || true
        rst_rule_present && log "kernel RST suppression active (iptables: $IPT_CHAIN)"
    else
        log "WARNING: neither nft nor iptables is available; l3 tunnels may be broken by kernel RSTs"
    fi
}

if [ "$exit_mode" = "l3" ] && [ "$suppress_rst" = "1" ]; then
    # Instances start in parallel and share one nft table/iptables chain;
    # serialize the install so two runners do not add the same rule twice.
    if command -v flock >/dev/null 2>&1; then
        exec 9>/tmp/krot-openflux-rst.lock
        flock 9
    fi
    if rst_rule_present; then
        log "kernel RST suppression already active"
    else
        rst_rule_install
    fi
    if command -v flock >/dev/null 2>&1; then
        flock -u 9 2>/dev/null || true
    fi
fi

# ---------------------------------------------------------------------------
# Compose the command line
# ---------------------------------------------------------------------------

cd "$OF_DIR" || exit 1

set -- --role=exit --mode="$exit_mode" --transport="$transport"
case "$transport" in
    yandex|vyandex|mailru)
        set -- "$@" --url "$url"
        ;;
    cupsonline)
        # url here is the base64 room list produced by the exit node itself
        # (it is printed once at startup); keep it verbatim.
        set -- "$@" --url "$url"
        ;;
    oneme)
        set -- "$@" --maxToken "$max_token" --maxUid "$max_uid"
        ;;
esac

set -- "$@" --codec "$codec"
[ -n "$local_ip" ] && set -- "$@" --local-ip "$local_ip"
[ "$debug" = "1" ] && set -- "$@" --debug

# Optional AES-256-GCM: write the shared secret to a root-only file.
# The binary hard-fails on secrets shorter than 16 chars — reject early with
# a clear log line instead of a respawn loop.
if [ -n "$encryption_key" ]; then
    if [ "${#encryption_key}" -lt 16 ]; then
        log "ERROR: encryption_key is ${#encryption_key} chars; the binary requires at least 16. Not starting."
        exit 1
    fi
    KEY_FILE="${STATE_DIR}/${SECTION}.key"
    umask 077
    printf '%s' "$encryption_key" > "$KEY_FILE"
    umask 022
    set -- "$@" --encryption-key-file "$KEY_FILE"
fi

# l4 keeps a localhost-only SOCKS fallback listener (clients connect to the
# transport directly; the port is a fallback documented upstream as --socks5).
if [ "$exit_mode" = "l4" ]; then
    set -- "$@" --socks5 "127.0.0.1:${listen_port}"
fi

log "starting openflux ($transport, $exit_mode, batch=${batch_bytes}B/${batch_count}pkt/${batch_linger_ms}ms)"

# Export performance tuning env vars for the binary
export OPENFLUX_BATCH_BYTES="$batch_bytes"
export OPENFLUX_BATCH_COUNT="$batch_count"
export OPENFLUX_BATCH_LINGER_MS="$batch_linger_ms"
export OPENFLUX_VOLGA_WORKERS="$volga_workers"
export OPENFLUX_VOLGA_BATCH_SIZE="$volga_batch_size"
export OPENFLUX_VOLGA_BATCH_TIMEOUT_MS="$volga_batch_timeout"
export OPENFLUX_VOLGA_BATCH_BYTES="$volga_batch_bytes"

# Capture the binary's own stdout/stderr — procd would otherwise send it to
# /dev/null, hiding the crash reason in a respawn loop. Append so a respawn
# does not wipe the previous failure.
LOG_FILE="/tmp/openflux-${SECTION}.log"
{
    echo "=== $(date '+%Y-%m-%d %H:%M:%S') starting: $* ==="
    echo "=== env: OPENFLUX_BATCH_BYTES=$batch_bytes OPENFLUX_BATCH_COUNT=$batch_count OPENFLUX_BATCH_LINGER_MS=$batch_linger_ms ==="
    exec "$BIN" "$@"
} >>"$LOG_FILE" 2>&1
