blank_issues_enabled: false
contact_links:
  - name: 💬 Если у вас что-то не работает, прежде всего прочитайте README проекта
    url: https://github.com/titovcode/krot
  - name: Telegram
    url: https://github.com/titovcode/krot#readme
    about: README Podkop Plus
