import { defineConfig } from 'tsup';
import fs from 'fs';
import path from 'path';

export default defineConfig({
    entry: ['src/main.ts'],
    format: ['esm'],
    outDir: '../luci-app-krot/htdocs/luci-static/resources/view/podkop',
    outExtension: () => ({ js: '.js' }),
    dts: false,
    clean: false,
    sourcemap: false,
    minify: true,
    target: 'es2020',
    banner: {
        js: `// This file is autogenerated, please don't change manually \n"use strict";`,
    },
    esbuildOptions(options) {
        options.legalComments = 'none';
    },
    onSuccess: () => {
        const outDir =
            '../luci-app-krot/htdocs/luci-static/resources/view/podkop';
        const file = path.join(outDir, 'main.js');
        let code = fs.readFileSync(file, 'utf8');

        code = code.replace(
            /export\s*{([\s\S]*?)}/,
            (match, group) => {
                const parsedGroup = group
                    .split(',')
                    .map(item => {
                        const trimmed = item.trim();
                        if (!trimmed) return '';
                        const parts = trimmed.split(/\s+as\s+/);
                        if (parts.length === 2) {
                            return `${parts[1]}: ${parts[0]}`;
                        }
                        return trimmed;
                    })
                    .filter(Boolean)
                    .join(', ');
                return `return baseclass.extend({${parsedGroup}})`;
            }
        );

        fs.writeFileSync(file, code, 'utf8');
        console.log(`✅ Patched LuCI build: ${file}`);
    },
});
