#!/bin/sh /etc/rc.common
# krot-openflux: OpenFlux exit-node instances.
#
# Sources of instances: instance sections in /etc/config/krot_openflux
# (LuCI page: Services -> OpenFlux).

START=95
STOP=10
USE_PROCD=1

start_service() {
	. /lib/functions.sh

	[ -f /etc/config/krot_openflux ] || return 0
	config_load krot_openflux
	config_foreach start_openflux_instance instance
}

openflux_spawn() {
	local name="$1" section="$2"

	procd_open_instance "$name"
	procd_set_param command /bin/sh /usr/lib/krot-openflux/openflux-run.sh "$section"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file /etc/config/krot_openflux
	procd_close_instance
}

start_openflux_instance() {
	local section="$1"
	local enabled
	config_get_bool enabled "$section" enabled 0
	[ "$enabled" -eq 1 ] || return 0
	openflux_spawn "krot-openflux-$section" "$section"
}

reload_service() {
	restart
}

service_triggers() {
	procd_add_reload_trigger krot_openflux
}
